const tg=window.Telegram.WebApp;tg.ready();tg.expand();
const initData=tg.initData;const api=(path,opt={})=>fetch(path,{...opt,headers:{'Content-Type':'application/json','X-Telegram-Init-Data':initData,...(opt.headers||{})}}).then(async r=>{if(!r.ok)throw new Error(await r.text());return r.json()});
if(tg.colorScheme==='dark')document.body.classList.add('dark');
let state={tab:'dashboard',data:null,selected:new Set()};
const tabs=[['dashboard','🏠 Dashboard'],['kanban','🛡 Модерация'],['calendar','📅 Календарь'],['dialogs','💬 Поддержка'],['complaints','⚠️ Жалобы'],['analytics','📈 Аналитика'],['roles','👥 Роли'],['audit','📜 Журнал'],['notifications','🔔 Уведомления']];
function esc(x){return String(x??'').replace(/[&<>"']/g,m=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#039;'}[m]))}
function btn(t,fn,c='btn'){return `<button class="${c}" onclick="${fn}">${t}</button>`}
function nav(){document.querySelector('#tabs').innerHTML=tabs.map(x=>`<button onclick="setTab('${x[0]}')">${x[1]}</button>`).join('')}
async function setTab(t){state.tab=t;render();}
async function load(){state.data=await api('/admin/api/dashboard');document.querySelector('#role').textContent=state.data.me.role;nav();render()}
function render(){const c=document.querySelector('#content');if(state.tab==='dashboard')return dashboard(c);if(state.tab==='kanban')return kanban(c);if(state.tab==='calendar')return calendar(c);if(state.tab==='dialogs')return dialogs(c);if(state.tab==='complaints')return complaints(c);if(state.tab==='analytics')return analytics(c);if(state.tab==='roles')return roles(c);if(state.tab==='audit')return audit(c);if(state.tab==='notifications')return notifications(c)}
function dashboard(c){const s=state.data.stats;c.innerHTML=`<div class="grid">${[['👥',s.users],['📚',s.total],['⏳',s.waiting],['🗓',s.scheduled],['🚀',s.publishing],['✅',s.published],['❌',s.rejected],['💬',s.support.open]].map(x=>`<div class="card"><div>${x[0]}</div><div class="stat">${x[1]}</div></div>`).join('')}</div><div class="card"><h3>⚠️ SLA</h3>${state.data.sla_breaches.length?state.data.sla_breaches.map(x=>`<div>${x.id} — ${x.priority}</div>`).join(''): 'Нет просроченных обращений'}</div><div class="card"><h3>🏆 Лучшие истории</h3>${state.data.top_stories.map(x=>`#${x.id} — ${x.reactions} реакций`).join('<br>')||'Нет данных'}</div>`}
async function kanban(c){const d=await api('/admin/api/stories');const groups={waiting:[],publishing:[],scheduled:[],published:[],rejected:[]};d.items.forEach(x=>{let k=x.status;if(k==='waiting'&&x.scheduled_at)k='scheduled';if(groups[k])groups[k].push(x)});c.innerHTML=`<div class="row">${btn('☑️ Выбрать всё','selectAll()')} ${btn('❌ Массово отклонить','bulkReject()','btn danger')} ${btn('🗓 Снять расписание','bulkUnschedule()')}</div><div class="kanban">${[['waiting','⏳ Новые'],['publishing','🚀 Публикация'],['scheduled','🗓 Запланированы'],['published','✅ Опубликованы'],['rejected','❌ Отклонены']].map(([k,t])=>`<section class="column" ondragover="event.preventDefault()" ondrop="dropStory(event,'${k}')"><h3>${t}</h3>${groups[k].map(storyCard).join('')}</section>`).join('')}</div>`}
function storyCard(x){return `<article class="story" draggable="true" ondragstart="event.dataTransfer.setData('id','${x.id}')" onclick="openStory(${x.id})"><label onclick="event.stopPropagation()"><input type="checkbox" onchange="toggleSelect(${x.id},this.checked)"></label><b>#${x.id}</b> <span class="badge">${esc(x.category||'без темы')}</span><p>${esc((x.text||'').slice(0,180))}</p>${x.scheduled_at?`<small>🗓 ${esc(x.scheduled_at)}</small>`:''}</article>`}
async function openStory(id){const d=await api('/admin/api/story/'+id);const s=d.story;document.body.insertAdjacentHTML('beforeend',`<div class="modal" id="modal"><div class="sheet"><h2>История #${s.id}</h2><p>User: ${s.user_id}</p><textarea id="storyText">${esc(s.text)}</textarea><textarea id="postText">${esc(s.post_text||'')}</textarea><div class="actions">${btn('💾 Сохранить','saveStory('+id+')','btn primary')}${btn('🤖 ИИ','retryAI('+id+')')}${btn('🛡 Проверка ИИ','moderateAI('+id+')')}${btn('👀 Предпросмотр','previewStory('+id+')')}${btn('🚀 Опубликовать','publishStory('+id+')','btn ok')}${btn('❌ Отклонить','rejectStory('+id+')','btn danger')}${btn('🗓 Запланировать','scheduleStory('+id+')')}${btn('👤 Написать пользователю','contactUser('+id+')')}</div><h3>BC — Версии</h3>${d.versions.map(v=>`<div class="card">v${v.version_no} · ${esc(v.change_type)}<br>${btn('↩️ Восстановить','restoreVersion('+v.id+')')}</div>`).join('')} ${btn('Закрыть',"document.getElementById('modal').remove()")}</div></div>`) }
async function saveStory(id){await api('/admin/api/story/'+id,{method:'PUT',body:JSON.stringify({text:document.getElementById('storyText').value,post_text:document.getElementById('postText').value})});alert('Сохранено')}
async function retryAI(id){await api('/admin/api/story/'+id+'/ai',{method:'POST'});alert('ИИ обновлён')}
async function moderateAI(id){await api('/admin/api/story/'+id+'/ai-moderate',{method:'POST'});alert('Проверка ИИ завершена')}
async function publishStory(id){if(!confirm('Первое подтверждение: опубликовать историю?'))return;if(!confirm('Второе подтверждение: действие необратимо и история появится в канале. Продолжить?'))return;await api('/admin/api/story/'+id+'/publish',{method:'POST'});document.getElementById('modal').remove();render()}
async function rejectStory(id){if(!confirm('Отклонить историю?'))return;const reason=prompt('Причина');if(reason===null)return;await api('/admin/api/story/'+id+'/reject',{method:'POST',body:JSON.stringify({reason})});document.getElementById('modal').remove();render()}
async function previewStory(id){const d=await api('/admin/api/story/'+id);alert((d.story.post_text||d.story.text||'').slice(0,4000))}
async function contactUser(id){await api('/admin/api/story/'+id+'/contact',{method:'POST'});alert('Пользователю отправлено уведомление')}
async function scheduleStory(id){const raw=prompt('Дата/время. Например 2026-08-20T18:30');if(!raw)return;await api('/admin/api/story/'+id+'/schedule',{method:'POST',body:JSON.stringify({scheduled_at:raw})});alert('Запланировано')}
async function restoreVersion(id){await api('/admin/api/version/'+id+'/restore',{method:'POST'});alert('Версия восстановлена');document.getElementById('modal').remove()}
function toggleSelect(id,on){on?state.selected.add(id):state.selected.delete(id)}
async function dropStory(event,status){const id=event.dataTransfer.getData('id');if(status==='rejected')await api('/admin/api/story/'+id+'/reject',{method:'POST',body:JSON.stringify({reason:'Перемещено в отклонённые через Mini App'})});else if(status==='scheduled')await scheduleStory(id);else if(status==='published')await publishStory(id);render()}
async function selectAll(){document.querySelectorAll('.story input').forEach(x=>{x.checked=true;toggleSelect(x.closest('.story').querySelector('b').textContent.slice(1),true)})}
async function bulkReject(){await api('/admin/api/bulk',{method:'POST',body:JSON.stringify({ids:[...state.selected],action:'reject'})});state.selected.clear();render()}
async function bulkUnschedule(){await api('/admin/api/bulk',{method:'POST',body:JSON.stringify({ids:[...state.selected],action:'unschedule'})});state.selected.clear();render()}
async function calendar(c){const d=await api('/admin/api/stories?status=waiting');const items=d.items.filter(x=>x.scheduled_at);c.innerHTML=`<h2>BA — Календарь</h2><div class="calendar">${Array.from({length:35},(_,i)=>`<div class="day"><b>${i+1}</b>${items.filter(x=>new Date(x.scheduled_at).getDate()===i+1).map(x=>`<div>#${x.id}</div>`).join('')}</div>`).join('')}</div>`}
async function dialogs(c){const d=await api('/admin/api/dialogs');c.innerHTML=`<h2>AJ–AN — Поддержка</h2>${d.items.map(x=>`<div class="card"><b>#${x.id}</b> User ${x.user_id}<br>${esc(x.first_message||'')}<div class="actions">${btn('🔴 Critical',"setPriority("+x.id+",'critical')")}${btn('🟠 High',"setPriority("+x.id+",'high')")}${btn('🟡 Normal',"setPriority("+x.id+",'normal')")}${btn('🟢 Low',"setPriority("+x.id+",'low')")}${btn('👤 Назначить себе',"dialogAction("+x.id+",'assign')")}${btn('⏳ Ждём пользователя',"dialogAction("+x.id+",'waiting')")}${btn('✅ Решён',"dialogAction("+x.id+",'resolved')")}${btn('🔴 Закрыть',"dialogAction("+x.id+",'close')")}</div><textarea id="msg${x.id}" placeholder="Ответ пользователю"></textarea>${btn('💬 Отправить',"sendDialog("+x.id+")",'btn primary')}</div>`).join('')||'Нет открытых диалогов'}`}
async function sendDialog(id){const el=document.getElementById('msg'+id);if(!el.value.trim())return;await api('/admin/api/dialog/'+id+'/message',{method:'POST',body:JSON.stringify({text:el.value})});el.value='';render()}
async function dialogAction(id,a){await api('/admin/api/dialog/'+id+'/'+a,{method:'POST'});render()}
async function setPriority(id,p){await api('/admin/api/dialog/'+id,{method:'PUT',body:JSON.stringify({priority:p})});render()}
async function complaints(c){const d=await api('/admin/api/complaints');c.innerHTML=`<h2>AB — Жалобы</h2>${d.items.map(x=>`<div class="card"><b>#${x.story_id}</b> ${esc(x.reason)}<br>Статус: ${x.status} · Приоритет: ${x.priority}<div class="actions">${btn('В работу',"complaintUpdate("+x.id+",'in_progress') )}${btn('Закрыть',"complaintUpdate("+x.id+",'closed') )}</div></div>`).join('')||'Жалоб нет'}`}
async function complaintUpdate(id,status){await api('/admin/api/complaint/'+id,{method:'PUT',body:JSON.stringify({status})});render()}
async function analytics(c){const d=await api('/admin/api/analytics');c.innerHTML=`<h2>AS — Аналитика</h2><div class="grid"><div class="card">👥 ${d.analytics.users}</div><div class="card">📚 ${d.analytics.stories}</div><div class="card">❤️ ${d.analytics.reactions}</div><div class="card">💬 ${d.analytics.dialogs}</div></div><div class="card"><h3>AT — Retention</h3>1d: ${d.retention.d1||0}<br>7d: ${d.retention.d7||0}<br>30d: ${d.retention.d30||0}</div><div class="card"><h3>AU — Лучшие темы/истории</h3>${d.top.map(x=>`#${x.id} — ${x.reactions} реакций`).join('<br>')}</div><div class="card"><h3>AW — Эффективность модераторов</h3>${d.moderators.map(x=>`${x.admin_id}: ${x.action} — ${x.count}`).join('<br>')}</div>`}
async function roles(c){const d=await api('/admin/api/roles');c.innerHTML=`<h2>AO — Роли</h2>${d.items.map(x=>`<div class="card"><b>${x.user_id}</b> — ${x.role}<select onchange="setRole(${x.user_id},this.value)"><option>owner</option><option>moderator</option><option>support</option><option>analyst</option><option>editor</option></select></div>`).join('')}`}
async function setRole(id,role){await api('/admin/api/role/'+id,{method:'PUT',body:JSON.stringify({role})})}
async function audit(c){const d=await api('/admin/api/audit');c.innerHTML=`<h2>AP — Аудит</h2>${d.items.map(x=>`<div class="card">${esc(x.created_at)} · ${x.admin_id} · ${esc(x.action)}<br>${esc(x.details||'')}</div>`).join('')}`}
async function notifications(c){const d=await api('/admin/api/notifications');c.innerHTML=`<h2>BF — Уведомления</h2>${d.items.map(x=>`<div class="card"><b>${esc(x.title)}</b><p>${esc(x.body)}</p>${x.read_at?'':'🔵 Непрочитано'}</div>`).join('')}`}
load().catch(e=>{document.querySelector('#content').innerHTML='<div class="card">❌ '+esc(e.message)+'</div>'});
