"""Staff/LMS/KPI/AI operations foundation."""
from alembic import op
import sqlalchemy as sa
revision="0002_staff_lms_kpi_ai_ops"; down_revision="0001_initial_schema"; branch_labels=None; depends_on=None
ID=sa.BigInteger
def table(name,*cols): op.create_table(name,*cols)
def upgrade():
 table("employee_profiles",sa.Column("admin_id",ID,primary_key=True),sa.Column("full_name",sa.Text),sa.Column("position",sa.Text,nullable=False,server_default="moderator"),sa.Column("status",sa.Text,nullable=False,server_default="trainee"),sa.Column("work_started_at",sa.DateTime),sa.Column("fired_at",sa.DateTime),sa.Column("notes",sa.Text),sa.Column("created_at",sa.DateTime,server_default=sa.text("CURRENT_TIMESTAMP")),sa.Column("updated_at",sa.DateTime,server_default=sa.text("CURRENT_TIMESTAMP")))
 table("permission_catalog",sa.Column("key",sa.Text,primary_key=True),sa.Column("title",sa.Text,nullable=False),sa.Column("description",sa.Text))
 table("employee_permissions",sa.Column("admin_id",ID,primary_key=True),sa.Column("permission",sa.Text,primary_key=True),sa.Column("enabled",sa.Boolean,nullable=False,server_default=sa.text("false")),sa.Column("updated_by",ID),sa.Column("updated_at",sa.DateTime,server_default=sa.text("CURRENT_TIMESTAMP")))
 table("employee_role_history",sa.Column("id",ID,primary_key=True,autoincrement=True),sa.Column("admin_id",ID,nullable=False),sa.Column("old_role",sa.Text),sa.Column("new_role",sa.Text,nullable=False),sa.Column("changed_by",ID,nullable=False),sa.Column("reason",sa.Text),sa.Column("created_at",sa.DateTime,server_default=sa.text("CURRENT_TIMESTAMP")))
 table("employee_promotion_history",sa.Column("id",ID,primary_key=True,autoincrement=True),sa.Column("admin_id",ID,nullable=False),sa.Column("old_status",sa.Text),sa.Column("new_status",sa.Text,nullable=False),sa.Column("changed_by",ID,nullable=False),sa.Column("reason",sa.Text),sa.Column("created_at",sa.DateTime,server_default=sa.text("CURRENT_TIMESTAMP")))
 table("employee_violations",sa.Column("id",ID,primary_key=True,autoincrement=True),sa.Column("admin_id",ID,nullable=False),sa.Column("severity",sa.Text,nullable=False,server_default="normal"),sa.Column("reason",sa.Text,nullable=False),sa.Column("created_by",ID,nullable=False),sa.Column("resolved",sa.Boolean,nullable=False,server_default=sa.text("false")),sa.Column("created_at",sa.DateTime,server_default=sa.text("CURRENT_TIMESTAMP")))
 table("lms_courses",sa.Column("id",ID,primary_key=True,autoincrement=True),sa.Column("title",sa.Text,nullable=False),sa.Column("position",sa.Text),sa.Column("required",sa.Boolean,nullable=False,server_default=sa.text("false")),sa.Column("required_for_permission",sa.Text),sa.Column("deadline_days",sa.Integer,server_default="7"),sa.Column("active",sa.Boolean,nullable=False,server_default=sa.text("true")),sa.Column("created_at",sa.DateTime,server_default=sa.text("CURRENT_TIMESTAMP")))
 table("lms_lessons",sa.Column("id",ID,primary_key=True,autoincrement=True),sa.Column("course_id",ID,nullable=False),sa.Column("title",sa.Text,nullable=False),sa.Column("content",sa.Text),sa.Column("position",sa.Integer,nullable=False,server_default="0"),sa.ForeignKeyConstraint(["course_id"],["lms_courses.id"]))
 table("lms_tests",sa.Column("id",ID,primary_key=True,autoincrement=True),sa.Column("lesson_id",ID,nullable=False),sa.Column("question",sa.Text,nullable=False),sa.Column("options",sa.Text),sa.Column("correct_answer",sa.Text),sa.Column("points",sa.Integer,nullable=False,server_default="1"),sa.ForeignKeyConstraint(["lesson_id"],["lms_lessons.id"]))
 table("lms_assignments",sa.Column("id",ID,primary_key=True,autoincrement=True),sa.Column("admin_id",ID,nullable=False),sa.Column("course_id",ID,nullable=False),sa.Column("status",sa.Text,nullable=False,server_default="assigned"),sa.Column("progress",sa.Integer,nullable=False,server_default="0"),sa.Column("due_at",sa.DateTime),sa.Column("completed_at",sa.DateTime),sa.Column("created_at",sa.DateTime,server_default=sa.text("CURRENT_TIMESTAMP")))
 table("lms_attempts",sa.Column("id",ID,primary_key=True,autoincrement=True),sa.Column("assignment_id",ID,nullable=False),sa.Column("score",sa.Float),sa.Column("passed",sa.Boolean,nullable=False,server_default=sa.text("false")),sa.Column("answers",sa.Text),sa.Column("created_at",sa.DateTime,server_default=sa.text("CURRENT_TIMESTAMP")))
 table("lms_certificates",sa.Column("id",ID,primary_key=True,autoincrement=True),sa.Column("admin_id",ID,nullable=False),sa.Column("course_id",ID,nullable=False),sa.Column("certificate_no",sa.Text,nullable=False),sa.Column("issued_at",sa.DateTime,server_default=sa.text("CURRENT_TIMESTAMP")),sa.Column("expires_at",sa.DateTime))
 table("moderator_kpi_daily",sa.Column("id",ID,primary_key=True,autoincrement=True),sa.Column("admin_id",ID,nullable=False),sa.Column("day",sa.Date,nullable=False),sa.Column("moderated",sa.Integer,server_default="0"),sa.Column("published",sa.Integer,server_default="0"),sa.Column("errors",sa.Integer,server_default="0"),sa.Column("dangerous",sa.Integer,server_default="0"),sa.Column("support_responses",sa.Integer,server_default="0"),sa.Column("response_seconds",sa.BigInteger,server_default="0"),sa.Column("moderation_seconds",sa.BigInteger,server_default="0"),sa.Column("post_corrections",sa.Integer,server_default="0"),sa.Column("ai_risk_sum",sa.Float,server_default="0"),sa.Column("ai_confidence_sum",sa.Float,server_default="0"),sa.UniqueConstraint("admin_id","day",name="uq_kpi_admin_day"))
 table("ai_model_configs",sa.Column("model",sa.Text,primary_key=True),sa.Column("enabled",sa.Boolean,nullable=False,server_default=sa.text("true")),sa.Column("priority",sa.Integer,nullable=False,server_default="100"),sa.Column("max_tokens",sa.Integer,server_default="1800"),sa.Column("temperature",sa.Float,server_default="0.2"),sa.Column("updated_by",ID),sa.Column("updated_at",sa.DateTime,server_default=sa.text("CURRENT_TIMESTAMP")))
 table("ai_runs",sa.Column("id",ID,primary_key=True,autoincrement=True),sa.Column("story_id",ID),sa.Column("model",sa.Text,nullable=False),sa.Column("check_type",sa.Text,nullable=False),sa.Column("risk_score",sa.Float),sa.Column("confidence",sa.Float),sa.Column("passed",sa.Boolean),sa.Column("hallucination_flags",sa.Text),sa.Column("result",sa.Text),sa.Column("latency_ms",sa.Integer),sa.Column("created_at",sa.DateTime,server_default=sa.text("CURRENT_TIMESTAMP")))
 table("notification_events",sa.Column("id",ID,primary_key=True,autoincrement=True),sa.Column("admin_id",ID),sa.Column("kind",sa.Text,nullable=False),sa.Column("title",sa.Text,nullable=False),sa.Column("body",sa.Text,nullable=False),sa.Column("severity",sa.Text,server_default="info"),sa.Column("read_at",sa.DateTime),sa.Column("created_at",sa.DateTime,server_default=sa.text("CURRENT_TIMESTAMP")))
 table("deploy_events",sa.Column("id",ID,primary_key=True,autoincrement=True),sa.Column("environment",sa.Text,nullable=False),sa.Column("status",sa.Text,nullable=False),sa.Column("commit_sha",sa.Text),sa.Column("details",sa.Text),sa.Column("created_at",sa.DateTime,server_default=sa.text("CURRENT_TIMESTAMP")))
 table("load_test_runs",sa.Column("id",ID,primary_key=True,autoincrement=True),sa.Column("requests",sa.Integer),sa.Column("concurrency",sa.Integer),sa.Column("rps",sa.Float),sa.Column("failed",sa.Integer),sa.Column("created_at",sa.DateTime,server_default=sa.text("CURRENT_TIMESTAMP")))
 for k,title in [("story.view","Просмотр историй"),("story.edit","Редактирование"),("story.publish","Публикация"),("story.reject","Отклонение"),("story.ai","AI-проверки"),("support.reply","Ответ поддержки"),("training.manage","Управление обучением"),("employees.manage","Управление сотрудниками"),("roles.manage","Управление ролями"),("settings.manage","Настройки"),("monitoring.view","Мониторинг"),("audit.view","Аудит")]: op.execute(sa.text("INSERT INTO permission_catalog(key,title) VALUES (:k,:t) ON CONFLICT DO NOTHING").bindparams(k=k,t=title))
 op.create_index("ix_ai_runs_story_created","ai_runs",["story_id","created_at"]); op.create_index("ix_kpi_day","moderator_kpi_daily",["day"]); op.create_index("ix_lms_assignment_admin","lms_assignments",["admin_id","status"]); op.create_index("ix_notification_admin_read","notification_events",["admin_id","read_at"])
def downgrade():
 for n in ["load_test_runs","deploy_events","notification_events","ai_runs","ai_model_configs","moderator_kpi_daily","lms_certificates","lms_attempts","lms_assignments","lms_tests","lms_lessons","lms_courses","employee_violations","employee_promotion_history","employee_role_history","employee_permissions","permission_catalog","employee_profiles"]: op.drop_table(n)
